dist: trusty
sudo: required

language: java

jdk:
- openjdk8

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

addons:
  chrome: stable
  sonarcloud:
    organization: "varadha2k"
    token:
      secure: "47acd7981f33fb8e35f18977e208d850853bfbed" # encrypted value of your token

cache:
  directories:
    $HOME/.m2/repository
    $HOME/.sonar/cache
    $HOME/.gradle
    .gradle
  
script:
  - ./gradlew clean check build sonarqube
  
  