trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle
  
steps:
- task: Gradle@2
  displayName: Run Unit Test
  inputs:
    tasks: 'test'
    testRunTitle: 'Unit Test'
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/test/TEST-*.xml'
    sonarQubeRunAnalysis: false
    sqGradlePluginVersionChoice: 'specify'
    sonarQubeGradlePluginVersion: '2.6.1'
    checkStyleRunAnalysis: true
    findBugsRunAnalysis: true
    pmdRunAnalysis: true
    codeCoverageToolOption: 'Cobertura'
   
- task: Gradle@2
  displayName: Run Integration Test
  inputs:
    tasks: 'integrationTest'
    testRunTitle: 'Integration Test'
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/integrationTest/TEST-*.xml'
    sonarQubeRunAnalysis: false
- task: Gradle@2
  displayName: Run Contract Test
  inputs:
    tasks: 'contractTest'
    testRunTitle: 'Contract Test'
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/contractTest/TEST-*.xml'
    sonarQubeRunAnalysis: false


- task: Cache@2
  inputs:
    key: 'gradle | "$(Agent.OS)"'
    restoreKeys: gradle
    path: $(GRADLE_USER_HOME)
  displayName: Gradle build cache

- script: |
    ./gradlew --build-cache build    
    # stop the Gradle daemon to ensure no files are left open (impacting the save cache operation later)
    ./gradlew --stop    
  displayName: Build